import request from "../utils/axios";
export default {
    //登录
    getLoginList:(params?:any)=>request({
        url:'/users/login',
        method:'POST',
        data:params,
        mock:false
    }),
    //验证码
    getCaptcha:(params?:any)=>request({
        url:'/users/captcha',
        method:'GET',
        data:params,
        mock:false
    }),
    //导出excel
    getExcel:(params?:any)=>request({
        url:'/users/excel',
        method:'POST',
        data:params,
        mock:false
    }),
    //无感刷新
    refreshToken:(params?:any)=>request({
        url:'/users/refresh',
        method:'GET',
        data:params,
        mock:false
    }),
    //welcome echarts图表
    getEchartsList:(params?:any)=>request({
        url:'/echarts/list',
        method:'GET',
        data:params,
        mock:false
    }),
    //左侧aside菜单
    getMenuList:(params?:any)=>request({
        url:'/menu/list',
        method:'GET',
        data:params,
        mock:false
    }),
    //左侧权限菜单
    getMenuPermissionList:(params?:any)=>request({
        url:'/users/permissionlist',
        method:'GET',
        data:params,
        mock:false
    }),
    //用户列表
    getUserList:(params?:any)=>request({
        url:'/users/list',
        method:'GET',
        data:params,
        mock:false
    }),
    //用户新增&编辑
    getUserOperateList:(params?:any)=>request({
        url:'/users/operate',
        method:'POST',
        data:params,
        mock:false
    }),
    //用户删除&批量删除
    getUserDeleteList:(params?:any)=>request({
        url:'/users/delete',
        method:'POST',
        data:params,
        mock:false
    }),
    //角色列表
    getRoleList:(params?:any)=>request({
        url:'/roles/list',
        method:'GET',
        data:params,
        mock:false
    }),
    //部门列表
    getDeptList:(params?:any)=>request({
        url:'/depts/list',
        method:'GET',
        data:params,
        mock:false
    }),
     //菜单创建&新增&编辑
     getMenuOperateList:(params?:any)=>request({
        url:'/menu/operate',
        method:'POST',
        data:params,
        mock:false
    }),
    //菜单删除
    getMenuDeleteList:(params?:any)=>request({
        url:'/menus/delete',
        method:'POST',
        data:params,
        mock:false
    }),
     //角色创建&编辑
     getRoleOperateList:(params?:any)=>request({
        url:'/roles/operate',
        method:'POST',
        data:params,
        mock:false
    }),
    //角色删除
    getRoleDeleteList:(params?:any)=>request({
        url:'/roles/delete',
        method:'POST',
        data:params,
        mock:false
    }),
    //设置权限
    setPermissionList:(params?:any)=>request({
        url:'/roles/permission',
        method:'POST',
        data:params,
        mock:false
    }),
    //部门创建&编辑
    getDeptOperateList:(params?:any)=>request({
        url:'/depts/operate',
        method:'POST',
        data:params,
        mock:false
    }),
    //部门删除
    getDeptDeleteList:(params?:any)=>request({
        url:'/depts/delete',
        method:'POST',
        data:params,
        mock:false
    }),
    //地图
    getEcharts:(params?:any)=>request({
        url:'/data-gl/asset/data/buildings.json',
        method:'GET',
        data:params,
        mock:true
    }),
    //审批休假创建/作废
    getLeaveOperate:(params?:any)=>request({
        url:'/leaves/operate',
        method:'POST',
        data:params,
        mock:false
    }),
    //审批休假列表
    getLeaveList:(params?:any)=>request({
        url:'/leaves/list',
        method:'GET',
        data:params,
        mock:false
    }),
    //审批休假通过/驳回
    getApprove:(params?:any)=>request({
        url:'/leaves/approve',
        method:'POST',
        data:params,
        mock:false
    }),
    //上传图片
    uploadImg:(params?:any)=>request({
        url:'/uploads/img2',
        method:'GET',
        data:params,
        mock:false
    }),
}